### ISSUE TITLE
Spike: Investigate DynamoDB Data schema

### ISSUE THREAD

**Issue by nmestrada** [nmestrada/wunschmacher#3]
what does dynmodb provide for us in terms of:
- users
- grouping user
- shape of stored data
- login with Oauth

**Comment by daemosity** [comment]
I think the main overview re: data and auth for Amplify is that Amplify is a heavily opinionated framework.

Most (if not all) interactions with AWS resources occur through the Amplify API/"backend" settings - via resources/data or resources/auth, etc.

## Data shape/access

While DynamoDB, a NoSQL key-value DB, is used as the backend, the Amplify framework has both the shape of the data (the schema) and its access rules (auth) defined via ORM in a very relational DB way.

DynamoDB doesn't directly handle user authentication - this is handled via Amazon Cognito (also controlled via Amplify's backend config), but does store the user data after auth.

Example: 
```ts
const schema = {
  User: a.model({
    // Basic user fields
    email: a.string().required(),
    status: a.string(),
    profile: a.model({
      firstName: a.string(),
      lastName: a.string()
    }),
    // OAuth related fields
    authProvider: a.string(),
    externalId: a.string()
  }).authorization([
    a => allow.owner(), // User can access their own data
    a => allow.public().to(['read']) // Public can read basic info
  ])
};
```

As seen above, Amplify also uses data schemas to determine privacy/authorization scopes:

```ts
const schema = {
  Group: a.model({
    name: a.string().required(),
    description: a.string(),
    // Create relationship with users
    members: a.hasMany('User'),
    // Permissions/roles within group
    roles: a.string().array()
  }).authorization([
    a => allow.groupsDefinedIn(['admin']),
    a => allow.public().to(['read'])
  ]),

  User: a.model({
    // Group relationships
    groups: a.belongsTo('Group'),
    // Other user fields...
  })
};
```

The various ways we can shape the data via Amplify includes [setting fields](https://docs.amplify.aws/react/build-a-backend/data/data-modeling/add-fields/) and [relationships](https://docs.amplify.aws/react/build-a-backend/data/data-modeling/relationships/)

## Authorization

Amplify has a "sign-in" component that can be used on the client side, which responds to how authorization has been configured in the backend

Backend Example:

```ts
import { a, defineData } from '@aws-amplify/backend';

const schema = {
  Todo: a.model({
    content: a.string().required(),
    isDone: a.boolean(),
    owner: a.string()
  }).authorization([
    // Allow authenticated users to perform all operations
    a => allow.owner(),  // This uses Cognito user pool authentication
    // Optionally allow public read access
    a => allow.public().to(['read'])
  ])
};

export const data = defineData({
  schema,
  authorizationModes: {
    // Set userPool as default auth mode
    defaultAuthorizationMode: 'userPool',
    // Configure API key as backup for public access
    apiKeyAuthorizationMode: {
      expiresInDays: 30
    }
  }
});
```

Setting more complicated auth scopes (outside of "owner access") seems a bit more complicated. We can set access by defined role:

```ts
// Design your groups hierarchy to stay within limits
export const schema = {
  Todo: a.model({
    content: a.string(),
    status: a.string(),
    category: a.string()
  }).authorization([
    // Access by defined roles
    a => allow.groups(['ADMIN', 'EDITOR', 'VIEWER']), // Better
    // Rather than many specific groups like:
    // ['TEAM_A_ADMIN', 'TEAM_A_EDITOR', 'TEAM_B_ADMIN', 'TEAM_B_EDITOR', ...]
  ])
}
```

But these roles are a [little more complicated to set up](https://docs.amplify.aws/react/build-a-backend/auth/concepts/user-groups/). I'm still looking into how these groups can be set-up programmatically, or if I'm chasing the wrong cat up a tree.

### Oauth

That said, Oauth appears to be [simple to set up](https://docs.amplify.aws/react/build-a-backend/auth/concepts/external-identity-providers/)

**Comment by nmestrada** [comment]
This is awesome Sean thanks for looking into this!, I think we can worry about setting up user groups later on I would say this spike is done. I think as a way to start we can create an issue that would cover: 
- Implement Oauth login  &  user can sign/login on landing page 
What do you think?

**Comment by daemosity** [comment]
Sounds great! I'll go ahead and create one.
